CREATE DATABASE notetube_dev;

-- 1. CREATE EXTENSION TO GENERATE UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CREATE USERS TABLE 
CREATE TABLE IF NOT EXISTS Users (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. CREATE DECKS TABLE 
CREATE TABLE IF NOT EXISTS Decks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  deck_name VARCHAR(255) NOT NULL,
  user_id UUID REFERENCES Users(id) ON DELETE CASCADE,
  color VARCHAR(7) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. CREATE CARDS TABLE 
CREATE TABLE IF NOT EXISTS Flashcards (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  front TEXT NOT NULL,
  back TEXT NOT NULL,
  deck_id UUID REFERENCES Decks(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. CREATE VIDEOS TABLE 
CREATE TABLE IF NOT EXISTS Videos (
  video_id VARCHAR(255) PRIMARY KEY,
  thumbnail_url TEXT NOT NULL,
  title VARCHAR(255) NOT NULL,
  note_id UUID REFERENCES Notes(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. CREATE CARDS TABLE 
CREATE TABLE IF NOT EXISTS Notes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  user_id UUID REFERENCES Users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
